/*
Configuration Api

Nice description goes here

API version: 1.14.0
Contact: support@capenetworks.com
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package config_api_client

import (
	"bytes"
	"encoding/json"
	"fmt"
)

// checks if the WirelessNetworksResponse type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &WirelessNetworksResponse{}

// WirelessNetworksResponse struct for WirelessNetworksResponse
type WirelessNetworksResponse struct {
	WirelessNetworks []WirelessNetworksItem `json:"wireless_networks"`
	Pagination       PaginationDetails      `json:"pagination"`
}

type _WirelessNetworksResponse WirelessNetworksResponse

// NewWirelessNetworksResponse instantiates a new WirelessNetworksResponse object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewWirelessNetworksResponse(wirelessNetworks []WirelessNetworksItem, pagination PaginationDetails) *WirelessNetworksResponse {
	this := WirelessNetworksResponse{}
	this.WirelessNetworks = wirelessNetworks
	this.Pagination = pagination
	return &this
}

// NewWirelessNetworksResponseWithDefaults instantiates a new WirelessNetworksResponse object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewWirelessNetworksResponseWithDefaults() *WirelessNetworksResponse {
	this := WirelessNetworksResponse{}
	return &this
}

// GetWirelessNetworks returns the WirelessNetworks field value
func (o *WirelessNetworksResponse) GetWirelessNetworks() []WirelessNetworksItem {
	if o == nil {
		var ret []WirelessNetworksItem
		return ret
	}

	return o.WirelessNetworks
}

// GetWirelessNetworksOk returns a tuple with the WirelessNetworks field value
// and a boolean to check if the value has been set.
func (o *WirelessNetworksResponse) GetWirelessNetworksOk() ([]WirelessNetworksItem, bool) {
	if o == nil {
		return nil, false
	}
	return o.WirelessNetworks, true
}

// SetWirelessNetworks sets field value
func (o *WirelessNetworksResponse) SetWirelessNetworks(v []WirelessNetworksItem) {
	o.WirelessNetworks = v
}

// GetPagination returns the Pagination field value
func (o *WirelessNetworksResponse) GetPagination() PaginationDetails {
	if o == nil {
		var ret PaginationDetails
		return ret
	}

	return o.Pagination
}

// GetPaginationOk returns a tuple with the Pagination field value
// and a boolean to check if the value has been set.
func (o *WirelessNetworksResponse) GetPaginationOk() (*PaginationDetails, bool) {
	if o == nil {
		return nil, false
	}
	return &o.Pagination, true
}

// SetPagination sets field value
func (o *WirelessNetworksResponse) SetPagination(v PaginationDetails) {
	o.Pagination = v
}

func (o WirelessNetworksResponse) MarshalJSON() ([]byte, error) {
	toSerialize, err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o WirelessNetworksResponse) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	toSerialize["wireless_networks"] = o.WirelessNetworks
	toSerialize["pagination"] = o.Pagination
	return toSerialize, nil
}

func (o *WirelessNetworksResponse) UnmarshalJSON(data []byte) (err error) {
	// This validates that all required properties are included in the JSON object
	// by unmarshalling the object into a generic map with string keys and checking
	// that every required field exists as a key in the generic map.
	requiredProperties := []string{
		"wireless_networks",
		"pagination",
	}

	allProperties := make(map[string]interface{})

	err = json.Unmarshal(data, &allProperties)

	if err != nil {
		return err
	}

	for _, requiredProperty := range requiredProperties {
		if _, exists := allProperties[requiredProperty]; !exists {
			return fmt.Errorf("no value given for required property %v", requiredProperty)
		}
	}

	varWirelessNetworksResponse := _WirelessNetworksResponse{}

	decoder := json.NewDecoder(bytes.NewReader(data))
	decoder.DisallowUnknownFields()
	err = decoder.Decode(&varWirelessNetworksResponse)

	if err != nil {
		return err
	}

	*o = WirelessNetworksResponse(varWirelessNetworksResponse)

	return err
}

type NullableWirelessNetworksResponse struct {
	value *WirelessNetworksResponse
	isSet bool
}

func (v NullableWirelessNetworksResponse) Get() *WirelessNetworksResponse {
	return v.value
}

func (v *NullableWirelessNetworksResponse) Set(val *WirelessNetworksResponse) {
	v.value = val
	v.isSet = true
}

func (v NullableWirelessNetworksResponse) IsSet() bool {
	return v.isSet
}

func (v *NullableWirelessNetworksResponse) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableWirelessNetworksResponse(val *WirelessNetworksResponse) *NullableWirelessNetworksResponse {
	return &NullableWirelessNetworksResponse{value: val, isSet: true}
}

func (v NullableWirelessNetworksResponse) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableWirelessNetworksResponse) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}
