/*
Configuration Api

Nice description goes here

API version: 1.4.0
Contact: support@capenetworks.com
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package config_api_client

import (
	"bytes"
	"encoding/json"
	"fmt"
)

// checks if the ReadinessErrorResponse type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &ReadinessErrorResponse{}

// ReadinessErrorResponse struct for ReadinessErrorResponse
type ReadinessErrorResponse struct {
	Data   map[string]string `json:"data"`
	Status string            `json:"status"`
}

type _ReadinessErrorResponse ReadinessErrorResponse

// NewReadinessErrorResponse instantiates a new ReadinessErrorResponse object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewReadinessErrorResponse(data map[string]string, status string) *ReadinessErrorResponse {
	this := ReadinessErrorResponse{}
	this.Data = data
	this.Status = status
	return &this
}

// NewReadinessErrorResponseWithDefaults instantiates a new ReadinessErrorResponse object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewReadinessErrorResponseWithDefaults() *ReadinessErrorResponse {
	this := ReadinessErrorResponse{}
	return &this
}

// GetData returns the Data field value
func (o *ReadinessErrorResponse) GetData() map[string]string {
	if o == nil {
		var ret map[string]string
		return ret
	}

	return o.Data
}

// GetDataOk returns a tuple with the Data field value
// and a boolean to check if the value has been set.
func (o *ReadinessErrorResponse) GetDataOk() (*map[string]string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.Data, true
}

// SetData sets field value
func (o *ReadinessErrorResponse) SetData(v map[string]string) {
	o.Data = v
}

// GetStatus returns the Status field value
func (o *ReadinessErrorResponse) GetStatus() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.Status
}

// GetStatusOk returns a tuple with the Status field value
// and a boolean to check if the value has been set.
func (o *ReadinessErrorResponse) GetStatusOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.Status, true
}

// SetStatus sets field value
func (o *ReadinessErrorResponse) SetStatus(v string) {
	o.Status = v
}

func (o ReadinessErrorResponse) MarshalJSON() ([]byte, error) {
	toSerialize, err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o ReadinessErrorResponse) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	toSerialize["data"] = o.Data
	toSerialize["status"] = o.Status
	return toSerialize, nil
}

func (o *ReadinessErrorResponse) UnmarshalJSON(data []byte) (err error) {
	// This validates that all required properties are included in the JSON object
	// by unmarshalling the object into a generic map with string keys and checking
	// that every required field exists as a key in the generic map.
	requiredProperties := []string{
		"data",
		"status",
	}

	allProperties := make(map[string]interface{})

	err = json.Unmarshal(data, &allProperties)

	if err != nil {
		return err
	}

	for _, requiredProperty := range requiredProperties {
		if _, exists := allProperties[requiredProperty]; !exists {
			return fmt.Errorf("no value given for required property %v", requiredProperty)
		}
	}

	varReadinessErrorResponse := _ReadinessErrorResponse{}

	decoder := json.NewDecoder(bytes.NewReader(data))
	decoder.DisallowUnknownFields()
	err = decoder.Decode(&varReadinessErrorResponse)

	if err != nil {
		return err
	}

	*o = ReadinessErrorResponse(varReadinessErrorResponse)

	return err
}

type NullableReadinessErrorResponse struct {
	value *ReadinessErrorResponse
	isSet bool
}

func (v NullableReadinessErrorResponse) Get() *ReadinessErrorResponse {
	return v.value
}

func (v *NullableReadinessErrorResponse) Set(val *ReadinessErrorResponse) {
	v.value = val
	v.isSet = true
}

func (v NullableReadinessErrorResponse) IsSet() bool {
	return v.isSet
}

func (v *NullableReadinessErrorResponse) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableReadinessErrorResponse(val *ReadinessErrorResponse) *NullableReadinessErrorResponse {
	return &NullableReadinessErrorResponse{value: val, isSet: true}
}

func (v NullableReadinessErrorResponse) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableReadinessErrorResponse) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}
