/*
Copyright 2025 Hewlett Packard Enterprise Development LP.
*/

/*
HPE Aruba Networking UXI Configuration

This document outlines the API contracts for HPE Aruba Networking UXI.

API version: 6.7.0
Contact: support@capenetworks.com
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package config_api_client

import (
	"bytes"
	"encoding/json"
	"fmt"
)

// checks if the AgentGroupAssignmentPostResponse type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &AgentGroupAssignmentPostResponse{}

// AgentGroupAssignmentPostResponse struct for AgentGroupAssignmentPostResponse
type AgentGroupAssignmentPostResponse struct {
	// The unique identifier of the agent group assignment
	Id string `json:"id"`
	// The group component of the agent group assignment
	Group AgentGroupAssignmentPostGroup `json:"group"`
	// The agent component of the agent group assignment
	Agent AgentGroupAssignmentPostAgent `json:"agent"`
	// The type of the resource.
	Type string `json:"type"`
}

type _AgentGroupAssignmentPostResponse AgentGroupAssignmentPostResponse

// NewAgentGroupAssignmentPostResponse instantiates a new AgentGroupAssignmentPostResponse object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewAgentGroupAssignmentPostResponse(
	id string,
	group AgentGroupAssignmentPostGroup,
	agent AgentGroupAssignmentPostAgent,
	type_ string,
) *AgentGroupAssignmentPostResponse {
	this := AgentGroupAssignmentPostResponse{}
	this.Id = id
	this.Group = group
	this.Agent = agent
	this.Type = type_
	return &this
}

// NewAgentGroupAssignmentPostResponseWithDefaults instantiates a new AgentGroupAssignmentPostResponse object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewAgentGroupAssignmentPostResponseWithDefaults() *AgentGroupAssignmentPostResponse {
	this := AgentGroupAssignmentPostResponse{}
	return &this
}

// GetId returns the Id field value
func (o *AgentGroupAssignmentPostResponse) GetId() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.Id
}

// GetIdOk returns a tuple with the Id field value
// and a boolean to check if the value has been set.
func (o *AgentGroupAssignmentPostResponse) GetIdOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.Id, true
}

// SetId sets field value
func (o *AgentGroupAssignmentPostResponse) SetId(v string) {
	o.Id = v
}

// GetGroup returns the Group field value
func (o *AgentGroupAssignmentPostResponse) GetGroup() AgentGroupAssignmentPostGroup {
	if o == nil {
		var ret AgentGroupAssignmentPostGroup
		return ret
	}

	return o.Group
}

// GetGroupOk returns a tuple with the Group field value
// and a boolean to check if the value has been set.
func (o *AgentGroupAssignmentPostResponse) GetGroupOk() (*AgentGroupAssignmentPostGroup, bool) {
	if o == nil {
		return nil, false
	}
	return &o.Group, true
}

// SetGroup sets field value
func (o *AgentGroupAssignmentPostResponse) SetGroup(v AgentGroupAssignmentPostGroup) {
	o.Group = v
}

// GetAgent returns the Agent field value
func (o *AgentGroupAssignmentPostResponse) GetAgent() AgentGroupAssignmentPostAgent {
	if o == nil {
		var ret AgentGroupAssignmentPostAgent
		return ret
	}

	return o.Agent
}

// GetAgentOk returns a tuple with the Agent field value
// and a boolean to check if the value has been set.
func (o *AgentGroupAssignmentPostResponse) GetAgentOk() (*AgentGroupAssignmentPostAgent, bool) {
	if o == nil {
		return nil, false
	}
	return &o.Agent, true
}

// SetAgent sets field value
func (o *AgentGroupAssignmentPostResponse) SetAgent(v AgentGroupAssignmentPostAgent) {
	o.Agent = v
}

// GetType returns the Type field value
func (o *AgentGroupAssignmentPostResponse) GetType() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.Type
}

// GetTypeOk returns a tuple with the Type field value
// and a boolean to check if the value has been set.
func (o *AgentGroupAssignmentPostResponse) GetTypeOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.Type, true
}

// SetType sets field value
func (o *AgentGroupAssignmentPostResponse) SetType(v string) {
	o.Type = v
}

func (o AgentGroupAssignmentPostResponse) MarshalJSON() ([]byte, error) {
	toSerialize, err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o AgentGroupAssignmentPostResponse) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	toSerialize["id"] = o.Id
	toSerialize["group"] = o.Group
	toSerialize["agent"] = o.Agent
	toSerialize["type"] = o.Type
	return toSerialize, nil
}

func (o *AgentGroupAssignmentPostResponse) UnmarshalJSON(data []byte) (err error) {
	// This validates that all required properties are included in the JSON object
	// by unmarshalling the object into a generic map with string keys and checking
	// that every required field exists as a key in the generic map.
	requiredProperties := []string{
		"id",
		"group",
		"agent",
		"type",
	}

	allProperties := make(map[string]interface{})

	err = json.Unmarshal(data, &allProperties)

	if err != nil {
		return err
	}

	for _, requiredProperty := range requiredProperties {
		if _, exists := allProperties[requiredProperty]; !exists {
			return fmt.Errorf("no value given for required property %v", requiredProperty)
		}
	}

	varAgentGroupAssignmentPostResponse := _AgentGroupAssignmentPostResponse{}

	decoder := json.NewDecoder(bytes.NewReader(data))
	decoder.DisallowUnknownFields()
	err = decoder.Decode(&varAgentGroupAssignmentPostResponse)

	if err != nil {
		return err
	}

	*o = AgentGroupAssignmentPostResponse(varAgentGroupAssignmentPostResponse)

	return err
}

type NullableAgentGroupAssignmentPostResponse struct {
	value *AgentGroupAssignmentPostResponse
	isSet bool
}

func (v NullableAgentGroupAssignmentPostResponse) Get() *AgentGroupAssignmentPostResponse {
	return v.value
}

func (v *NullableAgentGroupAssignmentPostResponse) Set(val *AgentGroupAssignmentPostResponse) {
	v.value = val
	v.isSet = true
}

func (v NullableAgentGroupAssignmentPostResponse) IsSet() bool {
	return v.isSet
}

func (v *NullableAgentGroupAssignmentPostResponse) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableAgentGroupAssignmentPostResponse(
	val *AgentGroupAssignmentPostResponse,
) *NullableAgentGroupAssignmentPostResponse {
	return &NullableAgentGroupAssignmentPostResponse{value: val, isSet: true}
}

func (v NullableAgentGroupAssignmentPostResponse) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableAgentGroupAssignmentPostResponse) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}
