/*
Copyright 2025 Hewlett Packard Enterprise Development LP.
*/

/*
HPE Aruba Networking UXI Configuration

This document outlines the API contracts for HPE Aruba Networking UXI.

API version: 6.7.0
Contact: support@capenetworks.com
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package config_api_client

import (
	"bytes"
	"encoding/json"
	"fmt"
)

// checks if the GroupsGetParent type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &GroupsGetParent{}

// GroupsGetParent struct for GroupsGetParent
type GroupsGetParent struct {
	// The unique identifier of the parent group
	Id string `json:"id"`
}

type _GroupsGetParent GroupsGetParent

// NewGroupsGetParent instantiates a new GroupsGetParent object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewGroupsGetParent(id string) *GroupsGetParent {
	this := GroupsGetParent{}
	this.Id = id
	return &this
}

// NewGroupsGetParentWithDefaults instantiates a new GroupsGetParent object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewGroupsGetParentWithDefaults() *GroupsGetParent {
	this := GroupsGetParent{}
	return &this
}

// GetId returns the Id field value
func (o *GroupsGetParent) GetId() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.Id
}

// GetIdOk returns a tuple with the Id field value
// and a boolean to check if the value has been set.
func (o *GroupsGetParent) GetIdOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.Id, true
}

// SetId sets field value
func (o *GroupsGetParent) SetId(v string) {
	o.Id = v
}

func (o GroupsGetParent) MarshalJSON() ([]byte, error) {
	toSerialize, err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o GroupsGetParent) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	toSerialize["id"] = o.Id
	return toSerialize, nil
}

func (o *GroupsGetParent) UnmarshalJSON(data []byte) (err error) {
	// This validates that all required properties are included in the JSON object
	// by unmarshalling the object into a generic map with string keys and checking
	// that every required field exists as a key in the generic map.
	requiredProperties := []string{
		"id",
	}

	allProperties := make(map[string]interface{})

	err = json.Unmarshal(data, &allProperties)

	if err != nil {
		return err
	}

	for _, requiredProperty := range requiredProperties {
		if _, exists := allProperties[requiredProperty]; !exists {
			return fmt.Errorf("no value given for required property %v", requiredProperty)
		}
	}

	varGroupsGetParent := _GroupsGetParent{}

	decoder := json.NewDecoder(bytes.NewReader(data))
	decoder.DisallowUnknownFields()
	err = decoder.Decode(&varGroupsGetParent)

	if err != nil {
		return err
	}

	*o = GroupsGetParent(varGroupsGetParent)

	return err
}

type NullableGroupsGetParent struct {
	value *GroupsGetParent
	isSet bool
}

func (v NullableGroupsGetParent) Get() *GroupsGetParent {
	return v.value
}

func (v *NullableGroupsGetParent) Set(val *GroupsGetParent) {
	v.value = val
	v.isSet = true
}

func (v NullableGroupsGetParent) IsSet() bool {
	return v.isSet
}

func (v *NullableGroupsGetParent) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableGroupsGetParent(val *GroupsGetParent) *NullableGroupsGetParent {
	return &NullableGroupsGetParent{value: val, isSet: true}
}

func (v NullableGroupsGetParent) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableGroupsGetParent) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}
