/*
Copyright 2024 Hewlett Packard Enterprise Development LP.
*/

/*
Configuration Api

Nice description goes here

API version: 5.17.0
Contact: support@capenetworks.com
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package config_api_client

import (
	"encoding/json"
)

// checks if the GroupsPatchRequest type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &GroupsPatchRequest{}

// GroupsPatchRequest struct for GroupsPatchRequest
type GroupsPatchRequest struct {
	Name *string `json:"name,omitempty"`
}

// NewGroupsPatchRequest instantiates a new GroupsPatchRequest object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewGroupsPatchRequest() *GroupsPatchRequest {
	this := GroupsPatchRequest{}
	return &this
}

// NewGroupsPatchRequestWithDefaults instantiates a new GroupsPatchRequest object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewGroupsPatchRequestWithDefaults() *GroupsPatchRequest {
	this := GroupsPatchRequest{}
	return &this
}

// GetName returns the Name field value if set, zero value otherwise.
func (o *GroupsPatchRequest) GetName() string {
	if o == nil || IsNil(o.Name) {
		var ret string
		return ret
	}
	return *o.Name
}

// GetNameOk returns a tuple with the Name field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *GroupsPatchRequest) GetNameOk() (*string, bool) {
	if o == nil || IsNil(o.Name) {
		return nil, false
	}
	return o.Name, true
}

// HasName returns a boolean if a field has been set.
func (o *GroupsPatchRequest) HasName() bool {
	if o != nil && !IsNil(o.Name) {
		return true
	}

	return false
}

// SetName gets a reference to the given string and assigns it to the Name field.
func (o *GroupsPatchRequest) SetName(v string) {
	o.Name = &v
}

func (o GroupsPatchRequest) MarshalJSON() ([]byte, error) {
	toSerialize, err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o GroupsPatchRequest) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	if !IsNil(o.Name) {
		toSerialize["name"] = o.Name
	}
	return toSerialize, nil
}

type NullableGroupsPatchRequest struct {
	value *GroupsPatchRequest
	isSet bool
}

func (v NullableGroupsPatchRequest) Get() *GroupsPatchRequest {
	return v.value
}

func (v *NullableGroupsPatchRequest) Set(val *GroupsPatchRequest) {
	v.value = val
	v.isSet = true
}

func (v NullableGroupsPatchRequest) IsSet() bool {
	return v.isSet
}

func (v *NullableGroupsPatchRequest) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableGroupsPatchRequest(val *GroupsPatchRequest) *NullableGroupsPatchRequest {
	return &NullableGroupsPatchRequest{value: val, isSet: true}
}

func (v NullableGroupsPatchRequest) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableGroupsPatchRequest) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}
