/*
Copyright 2024 Hewlett Packard Enterprise Development LP.
*/

/*
Configuration Api

Nice description goes here

API version: 5.18.0
Contact: support@capenetworks.com
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package config_api_client

import (
	"bytes"
	"encoding/json"
	"fmt"
)

// checks if the ServiceTestGroupAssignmentsGetItem type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &ServiceTestGroupAssignmentsGetItem{}

// ServiceTestGroupAssignmentsGetItem struct for ServiceTestGroupAssignmentsGetItem
type ServiceTestGroupAssignmentsGetItem struct {
	Id          string                                    `json:"id"`
	Group       ServiceTestGroupAssignmentsGetGroup       `json:"group"`
	ServiceTest ServiceTestGroupAssignmentsGetServiceTest `json:"serviceTest"`
	Type        string                                    `json:"type"`
}

type _ServiceTestGroupAssignmentsGetItem ServiceTestGroupAssignmentsGetItem

// NewServiceTestGroupAssignmentsGetItem instantiates a new ServiceTestGroupAssignmentsGetItem object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewServiceTestGroupAssignmentsGetItem(
	id string,
	group ServiceTestGroupAssignmentsGetGroup,
	serviceTest ServiceTestGroupAssignmentsGetServiceTest,
	type_ string,
) *ServiceTestGroupAssignmentsGetItem {
	this := ServiceTestGroupAssignmentsGetItem{}
	this.Id = id
	this.Group = group
	this.ServiceTest = serviceTest
	this.Type = type_
	return &this
}

// NewServiceTestGroupAssignmentsGetItemWithDefaults instantiates a new ServiceTestGroupAssignmentsGetItem object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewServiceTestGroupAssignmentsGetItemWithDefaults() *ServiceTestGroupAssignmentsGetItem {
	this := ServiceTestGroupAssignmentsGetItem{}
	return &this
}

// GetId returns the Id field value
func (o *ServiceTestGroupAssignmentsGetItem) GetId() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.Id
}

// GetIdOk returns a tuple with the Id field value
// and a boolean to check if the value has been set.
func (o *ServiceTestGroupAssignmentsGetItem) GetIdOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.Id, true
}

// SetId sets field value
func (o *ServiceTestGroupAssignmentsGetItem) SetId(v string) {
	o.Id = v
}

// GetGroup returns the Group field value
func (o *ServiceTestGroupAssignmentsGetItem) GetGroup() ServiceTestGroupAssignmentsGetGroup {
	if o == nil {
		var ret ServiceTestGroupAssignmentsGetGroup
		return ret
	}

	return o.Group
}

// GetGroupOk returns a tuple with the Group field value
// and a boolean to check if the value has been set.
func (o *ServiceTestGroupAssignmentsGetItem) GetGroupOk() (*ServiceTestGroupAssignmentsGetGroup, bool) {
	if o == nil {
		return nil, false
	}
	return &o.Group, true
}

// SetGroup sets field value
func (o *ServiceTestGroupAssignmentsGetItem) SetGroup(v ServiceTestGroupAssignmentsGetGroup) {
	o.Group = v
}

// GetServiceTest returns the ServiceTest field value
func (o *ServiceTestGroupAssignmentsGetItem) GetServiceTest() ServiceTestGroupAssignmentsGetServiceTest {
	if o == nil {
		var ret ServiceTestGroupAssignmentsGetServiceTest
		return ret
	}

	return o.ServiceTest
}

// GetServiceTestOk returns a tuple with the ServiceTest field value
// and a boolean to check if the value has been set.
func (o *ServiceTestGroupAssignmentsGetItem) GetServiceTestOk() (*ServiceTestGroupAssignmentsGetServiceTest, bool) {
	if o == nil {
		return nil, false
	}
	return &o.ServiceTest, true
}

// SetServiceTest sets field value
func (o *ServiceTestGroupAssignmentsGetItem) SetServiceTest(
	v ServiceTestGroupAssignmentsGetServiceTest,
) {
	o.ServiceTest = v
}

// GetType returns the Type field value
func (o *ServiceTestGroupAssignmentsGetItem) GetType() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.Type
}

// GetTypeOk returns a tuple with the Type field value
// and a boolean to check if the value has been set.
func (o *ServiceTestGroupAssignmentsGetItem) GetTypeOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.Type, true
}

// SetType sets field value
func (o *ServiceTestGroupAssignmentsGetItem) SetType(v string) {
	o.Type = v
}

func (o ServiceTestGroupAssignmentsGetItem) MarshalJSON() ([]byte, error) {
	toSerialize, err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o ServiceTestGroupAssignmentsGetItem) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	toSerialize["id"] = o.Id
	toSerialize["group"] = o.Group
	toSerialize["serviceTest"] = o.ServiceTest
	toSerialize["type"] = o.Type
	return toSerialize, nil
}

func (o *ServiceTestGroupAssignmentsGetItem) UnmarshalJSON(data []byte) (err error) {
	// This validates that all required properties are included in the JSON object
	// by unmarshalling the object into a generic map with string keys and checking
	// that every required field exists as a key in the generic map.
	requiredProperties := []string{
		"id",
		"group",
		"serviceTest",
		"type",
	}

	allProperties := make(map[string]interface{})

	err = json.Unmarshal(data, &allProperties)

	if err != nil {
		return err
	}

	for _, requiredProperty := range requiredProperties {
		if _, exists := allProperties[requiredProperty]; !exists {
			return fmt.Errorf("no value given for required property %v", requiredProperty)
		}
	}

	varServiceTestGroupAssignmentsGetItem := _ServiceTestGroupAssignmentsGetItem{}

	decoder := json.NewDecoder(bytes.NewReader(data))
	decoder.DisallowUnknownFields()
	err = decoder.Decode(&varServiceTestGroupAssignmentsGetItem)

	if err != nil {
		return err
	}

	*o = ServiceTestGroupAssignmentsGetItem(varServiceTestGroupAssignmentsGetItem)

	return err
}

type NullableServiceTestGroupAssignmentsGetItem struct {
	value *ServiceTestGroupAssignmentsGetItem
	isSet bool
}

func (v NullableServiceTestGroupAssignmentsGetItem) Get() *ServiceTestGroupAssignmentsGetItem {
	return v.value
}

func (v *NullableServiceTestGroupAssignmentsGetItem) Set(val *ServiceTestGroupAssignmentsGetItem) {
	v.value = val
	v.isSet = true
}

func (v NullableServiceTestGroupAssignmentsGetItem) IsSet() bool {
	return v.isSet
}

func (v *NullableServiceTestGroupAssignmentsGetItem) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableServiceTestGroupAssignmentsGetItem(
	val *ServiceTestGroupAssignmentsGetItem,
) *NullableServiceTestGroupAssignmentsGetItem {
	return &NullableServiceTestGroupAssignmentsGetItem{value: val, isSet: true}
}

func (v NullableServiceTestGroupAssignmentsGetItem) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableServiceTestGroupAssignmentsGetItem) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}
