/*
Copyright 2024 Hewlett Packard Enterprise Development LP.
*/

/*
Configuration Api

Nice description goes here

API version: 5.18.0
Contact: support@capenetworks.com
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package config_api_client

import (
	"bytes"
	"encoding/json"
	"fmt"
)

// checks if the NetworkGroupAssignmentPostNetwork type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &NetworkGroupAssignmentPostNetwork{}

// NetworkGroupAssignmentPostNetwork struct for NetworkGroupAssignmentPostNetwork
type NetworkGroupAssignmentPostNetwork struct {
	Id string `json:"id"`
}

type _NetworkGroupAssignmentPostNetwork NetworkGroupAssignmentPostNetwork

// NewNetworkGroupAssignmentPostNetwork instantiates a new NetworkGroupAssignmentPostNetwork object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewNetworkGroupAssignmentPostNetwork(id string) *NetworkGroupAssignmentPostNetwork {
	this := NetworkGroupAssignmentPostNetwork{}
	this.Id = id
	return &this
}

// NewNetworkGroupAssignmentPostNetworkWithDefaults instantiates a new NetworkGroupAssignmentPostNetwork object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewNetworkGroupAssignmentPostNetworkWithDefaults() *NetworkGroupAssignmentPostNetwork {
	this := NetworkGroupAssignmentPostNetwork{}
	return &this
}

// GetId returns the Id field value
func (o *NetworkGroupAssignmentPostNetwork) GetId() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.Id
}

// GetIdOk returns a tuple with the Id field value
// and a boolean to check if the value has been set.
func (o *NetworkGroupAssignmentPostNetwork) GetIdOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.Id, true
}

// SetId sets field value
func (o *NetworkGroupAssignmentPostNetwork) SetId(v string) {
	o.Id = v
}

func (o NetworkGroupAssignmentPostNetwork) MarshalJSON() ([]byte, error) {
	toSerialize, err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o NetworkGroupAssignmentPostNetwork) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	toSerialize["id"] = o.Id
	return toSerialize, nil
}

func (o *NetworkGroupAssignmentPostNetwork) UnmarshalJSON(data []byte) (err error) {
	// This validates that all required properties are included in the JSON object
	// by unmarshalling the object into a generic map with string keys and checking
	// that every required field exists as a key in the generic map.
	requiredProperties := []string{
		"id",
	}

	allProperties := make(map[string]interface{})

	err = json.Unmarshal(data, &allProperties)

	if err != nil {
		return err
	}

	for _, requiredProperty := range requiredProperties {
		if _, exists := allProperties[requiredProperty]; !exists {
			return fmt.Errorf("no value given for required property %v", requiredProperty)
		}
	}

	varNetworkGroupAssignmentPostNetwork := _NetworkGroupAssignmentPostNetwork{}

	decoder := json.NewDecoder(bytes.NewReader(data))
	decoder.DisallowUnknownFields()
	err = decoder.Decode(&varNetworkGroupAssignmentPostNetwork)

	if err != nil {
		return err
	}

	*o = NetworkGroupAssignmentPostNetwork(varNetworkGroupAssignmentPostNetwork)

	return err
}

type NullableNetworkGroupAssignmentPostNetwork struct {
	value *NetworkGroupAssignmentPostNetwork
	isSet bool
}

func (v NullableNetworkGroupAssignmentPostNetwork) Get() *NetworkGroupAssignmentPostNetwork {
	return v.value
}

func (v *NullableNetworkGroupAssignmentPostNetwork) Set(val *NetworkGroupAssignmentPostNetwork) {
	v.value = val
	v.isSet = true
}

func (v NullableNetworkGroupAssignmentPostNetwork) IsSet() bool {
	return v.isSet
}

func (v *NullableNetworkGroupAssignmentPostNetwork) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableNetworkGroupAssignmentPostNetwork(
	val *NetworkGroupAssignmentPostNetwork,
) *NullableNetworkGroupAssignmentPostNetwork {
	return &NullableNetworkGroupAssignmentPostNetwork{value: val, isSet: true}
}

func (v NullableNetworkGroupAssignmentPostNetwork) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableNetworkGroupAssignmentPostNetwork) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}
