/*
Configuration Api

Nice description goes here

API version: 1.9.0
Contact: support@capenetworks.com
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package config_api_client

import (
	"bytes"
	"encoding/json"
	"fmt"
)

// checks if the GroupsGetItem type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &GroupsGetItem{}

// GroupsGetItem struct for GroupsGetItem
type GroupsGetItem struct {
	Uid       string         `json:"uid"`
	Name      string         `json:"name"`
	Path      string         `json:"path"`
	ParentUid NullableString `json:"parent_uid"`
}

type _GroupsGetItem GroupsGetItem

// NewGroupsGetItem instantiates a new GroupsGetItem object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewGroupsGetItem(uid string, name string, path string, parentUid NullableString) *GroupsGetItem {
	this := GroupsGetItem{}
	this.Uid = uid
	this.Name = name
	this.Path = path
	this.ParentUid = parentUid
	return &this
}

// NewGroupsGetItemWithDefaults instantiates a new GroupsGetItem object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewGroupsGetItemWithDefaults() *GroupsGetItem {
	this := GroupsGetItem{}
	return &this
}

// GetUid returns the Uid field value
func (o *GroupsGetItem) GetUid() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.Uid
}

// GetUidOk returns a tuple with the Uid field value
// and a boolean to check if the value has been set.
func (o *GroupsGetItem) GetUidOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.Uid, true
}

// SetUid sets field value
func (o *GroupsGetItem) SetUid(v string) {
	o.Uid = v
}

// GetName returns the Name field value
func (o *GroupsGetItem) GetName() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.Name
}

// GetNameOk returns a tuple with the Name field value
// and a boolean to check if the value has been set.
func (o *GroupsGetItem) GetNameOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.Name, true
}

// SetName sets field value
func (o *GroupsGetItem) SetName(v string) {
	o.Name = v
}

// GetPath returns the Path field value
func (o *GroupsGetItem) GetPath() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.Path
}

// GetPathOk returns a tuple with the Path field value
// and a boolean to check if the value has been set.
func (o *GroupsGetItem) GetPathOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.Path, true
}

// SetPath sets field value
func (o *GroupsGetItem) SetPath(v string) {
	o.Path = v
}

// GetParentUid returns the ParentUid field value
// If the value is explicit nil, the zero value for string will be returned
func (o *GroupsGetItem) GetParentUid() string {
	if o == nil || o.ParentUid.Get() == nil {
		var ret string
		return ret
	}

	return *o.ParentUid.Get()
}

// GetParentUidOk returns a tuple with the ParentUid field value
// and a boolean to check if the value has been set.
// NOTE: If the value is an explicit nil, `nil, true` will be returned
func (o *GroupsGetItem) GetParentUidOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return o.ParentUid.Get(), o.ParentUid.IsSet()
}

// SetParentUid sets field value
func (o *GroupsGetItem) SetParentUid(v string) {
	o.ParentUid.Set(&v)
}

func (o GroupsGetItem) MarshalJSON() ([]byte, error) {
	toSerialize, err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o GroupsGetItem) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	toSerialize["uid"] = o.Uid
	toSerialize["name"] = o.Name
	toSerialize["path"] = o.Path
	toSerialize["parent_uid"] = o.ParentUid.Get()
	return toSerialize, nil
}

func (o *GroupsGetItem) UnmarshalJSON(data []byte) (err error) {
	// This validates that all required properties are included in the JSON object
	// by unmarshalling the object into a generic map with string keys and checking
	// that every required field exists as a key in the generic map.
	requiredProperties := []string{
		"uid",
		"name",
		"path",
		"parent_uid",
	}

	allProperties := make(map[string]interface{})

	err = json.Unmarshal(data, &allProperties)

	if err != nil {
		return err
	}

	for _, requiredProperty := range requiredProperties {
		if _, exists := allProperties[requiredProperty]; !exists {
			return fmt.Errorf("no value given for required property %v", requiredProperty)
		}
	}

	varGroupsGetItem := _GroupsGetItem{}

	decoder := json.NewDecoder(bytes.NewReader(data))
	decoder.DisallowUnknownFields()
	err = decoder.Decode(&varGroupsGetItem)

	if err != nil {
		return err
	}

	*o = GroupsGetItem(varGroupsGetItem)

	return err
}

type NullableGroupsGetItem struct {
	value *GroupsGetItem
	isSet bool
}

func (v NullableGroupsGetItem) Get() *GroupsGetItem {
	return v.value
}

func (v *NullableGroupsGetItem) Set(val *GroupsGetItem) {
	v.value = val
	v.isSet = true
}

func (v NullableGroupsGetItem) IsSet() bool {
	return v.isSet
}

func (v *NullableGroupsGetItem) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableGroupsGetItem(val *GroupsGetItem) *NullableGroupsGetItem {
	return &NullableGroupsGetItem{value: val, isSet: true}
}

func (v NullableGroupsGetItem) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableGroupsGetItem) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}
