/*
Configuration Api

Nice description goes here

API version: 5.6.0
Contact: support@capenetworks.com
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package config_api_client

import (
	"bytes"
	"encoding/json"
	"fmt"
)

// checks if the ServiceTestsListItem type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &ServiceTestsListItem{}

// ServiceTestsListItem struct for ServiceTestsListItem
type ServiceTestsListItem struct {
	Id        string         `json:"id"`
	Category  string         `json:"category"`
	Name      string         `json:"name"`
	Target    NullableString `json:"target"`
	Template  string         `json:"template"`
	IsEnabled bool           `json:"isEnabled"`
	Type      string         `json:"type"`
}

type _ServiceTestsListItem ServiceTestsListItem

// NewServiceTestsListItem instantiates a new ServiceTestsListItem object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewServiceTestsListItem(
	id string,
	category string,
	name string,
	target NullableString,
	template string,
	isEnabled bool,
	type_ string,
) *ServiceTestsListItem {
	this := ServiceTestsListItem{}
	this.Id = id
	this.Category = category
	this.Name = name
	this.Target = target
	this.Template = template
	this.IsEnabled = isEnabled
	this.Type = type_
	return &this
}

// NewServiceTestsListItemWithDefaults instantiates a new ServiceTestsListItem object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewServiceTestsListItemWithDefaults() *ServiceTestsListItem {
	this := ServiceTestsListItem{}
	return &this
}

// GetId returns the Id field value
func (o *ServiceTestsListItem) GetId() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.Id
}

// GetIdOk returns a tuple with the Id field value
// and a boolean to check if the value has been set.
func (o *ServiceTestsListItem) GetIdOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.Id, true
}

// SetId sets field value
func (o *ServiceTestsListItem) SetId(v string) {
	o.Id = v
}

// GetCategory returns the Category field value
func (o *ServiceTestsListItem) GetCategory() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.Category
}

// GetCategoryOk returns a tuple with the Category field value
// and a boolean to check if the value has been set.
func (o *ServiceTestsListItem) GetCategoryOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.Category, true
}

// SetCategory sets field value
func (o *ServiceTestsListItem) SetCategory(v string) {
	o.Category = v
}

// GetName returns the Name field value
func (o *ServiceTestsListItem) GetName() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.Name
}

// GetNameOk returns a tuple with the Name field value
// and a boolean to check if the value has been set.
func (o *ServiceTestsListItem) GetNameOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.Name, true
}

// SetName sets field value
func (o *ServiceTestsListItem) SetName(v string) {
	o.Name = v
}

// GetTarget returns the Target field value
// If the value is explicit nil, the zero value for string will be returned
func (o *ServiceTestsListItem) GetTarget() string {
	if o == nil || o.Target.Get() == nil {
		var ret string
		return ret
	}

	return *o.Target.Get()
}

// GetTargetOk returns a tuple with the Target field value
// and a boolean to check if the value has been set.
// NOTE: If the value is an explicit nil, `nil, true` will be returned
func (o *ServiceTestsListItem) GetTargetOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return o.Target.Get(), o.Target.IsSet()
}

// SetTarget sets field value
func (o *ServiceTestsListItem) SetTarget(v string) {
	o.Target.Set(&v)
}

// GetTemplate returns the Template field value
func (o *ServiceTestsListItem) GetTemplate() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.Template
}

// GetTemplateOk returns a tuple with the Template field value
// and a boolean to check if the value has been set.
func (o *ServiceTestsListItem) GetTemplateOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.Template, true
}

// SetTemplate sets field value
func (o *ServiceTestsListItem) SetTemplate(v string) {
	o.Template = v
}

// GetIsEnabled returns the IsEnabled field value
func (o *ServiceTestsListItem) GetIsEnabled() bool {
	if o == nil {
		var ret bool
		return ret
	}

	return o.IsEnabled
}

// GetIsEnabledOk returns a tuple with the IsEnabled field value
// and a boolean to check if the value has been set.
func (o *ServiceTestsListItem) GetIsEnabledOk() (*bool, bool) {
	if o == nil {
		return nil, false
	}
	return &o.IsEnabled, true
}

// SetIsEnabled sets field value
func (o *ServiceTestsListItem) SetIsEnabled(v bool) {
	o.IsEnabled = v
}

// GetType returns the Type field value
func (o *ServiceTestsListItem) GetType() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.Type
}

// GetTypeOk returns a tuple with the Type field value
// and a boolean to check if the value has been set.
func (o *ServiceTestsListItem) GetTypeOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.Type, true
}

// SetType sets field value
func (o *ServiceTestsListItem) SetType(v string) {
	o.Type = v
}

func (o ServiceTestsListItem) MarshalJSON() ([]byte, error) {
	toSerialize, err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o ServiceTestsListItem) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	toSerialize["id"] = o.Id
	toSerialize["category"] = o.Category
	toSerialize["name"] = o.Name
	toSerialize["target"] = o.Target.Get()
	toSerialize["template"] = o.Template
	toSerialize["isEnabled"] = o.IsEnabled
	toSerialize["type"] = o.Type
	return toSerialize, nil
}

func (o *ServiceTestsListItem) UnmarshalJSON(data []byte) (err error) {
	// This validates that all required properties are included in the JSON object
	// by unmarshalling the object into a generic map with string keys and checking
	// that every required field exists as a key in the generic map.
	requiredProperties := []string{
		"id",
		"category",
		"name",
		"target",
		"template",
		"isEnabled",
		"type",
	}

	allProperties := make(map[string]interface{})

	err = json.Unmarshal(data, &allProperties)

	if err != nil {
		return err
	}

	for _, requiredProperty := range requiredProperties {
		if _, exists := allProperties[requiredProperty]; !exists {
			return fmt.Errorf("no value given for required property %v", requiredProperty)
		}
	}

	varServiceTestsListItem := _ServiceTestsListItem{}

	decoder := json.NewDecoder(bytes.NewReader(data))
	decoder.DisallowUnknownFields()
	err = decoder.Decode(&varServiceTestsListItem)

	if err != nil {
		return err
	}

	*o = ServiceTestsListItem(varServiceTestsListItem)

	return err
}

type NullableServiceTestsListItem struct {
	value *ServiceTestsListItem
	isSet bool
}

func (v NullableServiceTestsListItem) Get() *ServiceTestsListItem {
	return v.value
}

func (v *NullableServiceTestsListItem) Set(val *ServiceTestsListItem) {
	v.value = val
	v.isSet = true
}

func (v NullableServiceTestsListItem) IsSet() bool {
	return v.isSet
}

func (v *NullableServiceTestsListItem) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableServiceTestsListItem(val *ServiceTestsListItem) *NullableServiceTestsListItem {
	return &NullableServiceTestsListItem{value: val, isSet: true}
}

func (v NullableServiceTestsListItem) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableServiceTestsListItem) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}
