/*
Configuration Api

Nice description goes here

API version: 1.15.0
Contact: support@capenetworks.com
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package config_api_client

import (
	"bytes"
	"encoding/json"
	"fmt"
)

// checks if the WiredNetworksResponse type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &WiredNetworksResponse{}

// WiredNetworksResponse struct for WiredNetworksResponse
type WiredNetworksResponse struct {
	WiredNetworks []WiredNetworksItem `json:"wired_networks"`
	Pagination    PaginationDetails   `json:"pagination"`
}

type _WiredNetworksResponse WiredNetworksResponse

// NewWiredNetworksResponse instantiates a new WiredNetworksResponse object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewWiredNetworksResponse(wiredNetworks []WiredNetworksItem, pagination PaginationDetails) *WiredNetworksResponse {
	this := WiredNetworksResponse{}
	this.WiredNetworks = wiredNetworks
	this.Pagination = pagination
	return &this
}

// NewWiredNetworksResponseWithDefaults instantiates a new WiredNetworksResponse object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewWiredNetworksResponseWithDefaults() *WiredNetworksResponse {
	this := WiredNetworksResponse{}
	return &this
}

// GetWiredNetworks returns the WiredNetworks field value
func (o *WiredNetworksResponse) GetWiredNetworks() []WiredNetworksItem {
	if o == nil {
		var ret []WiredNetworksItem
		return ret
	}

	return o.WiredNetworks
}

// GetWiredNetworksOk returns a tuple with the WiredNetworks field value
// and a boolean to check if the value has been set.
func (o *WiredNetworksResponse) GetWiredNetworksOk() ([]WiredNetworksItem, bool) {
	if o == nil {
		return nil, false
	}
	return o.WiredNetworks, true
}

// SetWiredNetworks sets field value
func (o *WiredNetworksResponse) SetWiredNetworks(v []WiredNetworksItem) {
	o.WiredNetworks = v
}

// GetPagination returns the Pagination field value
func (o *WiredNetworksResponse) GetPagination() PaginationDetails {
	if o == nil {
		var ret PaginationDetails
		return ret
	}

	return o.Pagination
}

// GetPaginationOk returns a tuple with the Pagination field value
// and a boolean to check if the value has been set.
func (o *WiredNetworksResponse) GetPaginationOk() (*PaginationDetails, bool) {
	if o == nil {
		return nil, false
	}
	return &o.Pagination, true
}

// SetPagination sets field value
func (o *WiredNetworksResponse) SetPagination(v PaginationDetails) {
	o.Pagination = v
}

func (o WiredNetworksResponse) MarshalJSON() ([]byte, error) {
	toSerialize, err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o WiredNetworksResponse) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	toSerialize["wired_networks"] = o.WiredNetworks
	toSerialize["pagination"] = o.Pagination
	return toSerialize, nil
}

func (o *WiredNetworksResponse) UnmarshalJSON(data []byte) (err error) {
	// This validates that all required properties are included in the JSON object
	// by unmarshalling the object into a generic map with string keys and checking
	// that every required field exists as a key in the generic map.
	requiredProperties := []string{
		"wired_networks",
		"pagination",
	}

	allProperties := make(map[string]interface{})

	err = json.Unmarshal(data, &allProperties)

	if err != nil {
		return err
	}

	for _, requiredProperty := range requiredProperties {
		if _, exists := allProperties[requiredProperty]; !exists {
			return fmt.Errorf("no value given for required property %v", requiredProperty)
		}
	}

	varWiredNetworksResponse := _WiredNetworksResponse{}

	decoder := json.NewDecoder(bytes.NewReader(data))
	decoder.DisallowUnknownFields()
	err = decoder.Decode(&varWiredNetworksResponse)

	if err != nil {
		return err
	}

	*o = WiredNetworksResponse(varWiredNetworksResponse)

	return err
}

type NullableWiredNetworksResponse struct {
	value *WiredNetworksResponse
	isSet bool
}

func (v NullableWiredNetworksResponse) Get() *WiredNetworksResponse {
	return v.value
}

func (v *NullableWiredNetworksResponse) Set(val *WiredNetworksResponse) {
	v.value = val
	v.isSet = true
}

func (v NullableWiredNetworksResponse) IsSet() bool {
	return v.isSet
}

func (v *NullableWiredNetworksResponse) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableWiredNetworksResponse(val *WiredNetworksResponse) *NullableWiredNetworksResponse {
	return &NullableWiredNetworksResponse{value: val, isSet: true}
}

func (v NullableWiredNetworksResponse) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableWiredNetworksResponse) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}
