/*
Copyright 2024 Hewlett Packard Enterprise Development LP.
*/

/*
HPE Aruba Networking UXI Configuration

This document outlines the API contracts for HPE Aruba Networking UXI.

API version: 5.19.0
Contact: support@capenetworks.com
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package config_api_client

import (
	"bytes"
	"encoding/json"
	"fmt"
)

// checks if the SensorGroupAssignmentsGetItem type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &SensorGroupAssignmentsGetItem{}

// SensorGroupAssignmentsGetItem struct for SensorGroupAssignmentsGetItem
type SensorGroupAssignmentsGetItem struct {
	Id     string                          `json:"id"`
	Group  SensorGroupAssignmentsGetGroup  `json:"group"`
	Sensor SensorGroupAssignmentsGetSensor `json:"sensor"`
	Type   string                          `json:"type"`
}

type _SensorGroupAssignmentsGetItem SensorGroupAssignmentsGetItem

// NewSensorGroupAssignmentsGetItem instantiates a new SensorGroupAssignmentsGetItem object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewSensorGroupAssignmentsGetItem(
	id string,
	group SensorGroupAssignmentsGetGroup,
	sensor SensorGroupAssignmentsGetSensor,
	type_ string,
) *SensorGroupAssignmentsGetItem {
	this := SensorGroupAssignmentsGetItem{}
	this.Id = id
	this.Group = group
	this.Sensor = sensor
	this.Type = type_
	return &this
}

// NewSensorGroupAssignmentsGetItemWithDefaults instantiates a new SensorGroupAssignmentsGetItem object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewSensorGroupAssignmentsGetItemWithDefaults() *SensorGroupAssignmentsGetItem {
	this := SensorGroupAssignmentsGetItem{}
	return &this
}

// GetId returns the Id field value
func (o *SensorGroupAssignmentsGetItem) GetId() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.Id
}

// GetIdOk returns a tuple with the Id field value
// and a boolean to check if the value has been set.
func (o *SensorGroupAssignmentsGetItem) GetIdOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.Id, true
}

// SetId sets field value
func (o *SensorGroupAssignmentsGetItem) SetId(v string) {
	o.Id = v
}

// GetGroup returns the Group field value
func (o *SensorGroupAssignmentsGetItem) GetGroup() SensorGroupAssignmentsGetGroup {
	if o == nil {
		var ret SensorGroupAssignmentsGetGroup
		return ret
	}

	return o.Group
}

// GetGroupOk returns a tuple with the Group field value
// and a boolean to check if the value has been set.
func (o *SensorGroupAssignmentsGetItem) GetGroupOk() (*SensorGroupAssignmentsGetGroup, bool) {
	if o == nil {
		return nil, false
	}
	return &o.Group, true
}

// SetGroup sets field value
func (o *SensorGroupAssignmentsGetItem) SetGroup(v SensorGroupAssignmentsGetGroup) {
	o.Group = v
}

// GetSensor returns the Sensor field value
func (o *SensorGroupAssignmentsGetItem) GetSensor() SensorGroupAssignmentsGetSensor {
	if o == nil {
		var ret SensorGroupAssignmentsGetSensor
		return ret
	}

	return o.Sensor
}

// GetSensorOk returns a tuple with the Sensor field value
// and a boolean to check if the value has been set.
func (o *SensorGroupAssignmentsGetItem) GetSensorOk() (*SensorGroupAssignmentsGetSensor, bool) {
	if o == nil {
		return nil, false
	}
	return &o.Sensor, true
}

// SetSensor sets field value
func (o *SensorGroupAssignmentsGetItem) SetSensor(v SensorGroupAssignmentsGetSensor) {
	o.Sensor = v
}

// GetType returns the Type field value
func (o *SensorGroupAssignmentsGetItem) GetType() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.Type
}

// GetTypeOk returns a tuple with the Type field value
// and a boolean to check if the value has been set.
func (o *SensorGroupAssignmentsGetItem) GetTypeOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.Type, true
}

// SetType sets field value
func (o *SensorGroupAssignmentsGetItem) SetType(v string) {
	o.Type = v
}

func (o SensorGroupAssignmentsGetItem) MarshalJSON() ([]byte, error) {
	toSerialize, err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o SensorGroupAssignmentsGetItem) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	toSerialize["id"] = o.Id
	toSerialize["group"] = o.Group
	toSerialize["sensor"] = o.Sensor
	toSerialize["type"] = o.Type
	return toSerialize, nil
}

func (o *SensorGroupAssignmentsGetItem) UnmarshalJSON(data []byte) (err error) {
	// This validates that all required properties are included in the JSON object
	// by unmarshalling the object into a generic map with string keys and checking
	// that every required field exists as a key in the generic map.
	requiredProperties := []string{
		"id",
		"group",
		"sensor",
		"type",
	}

	allProperties := make(map[string]interface{})

	err = json.Unmarshal(data, &allProperties)

	if err != nil {
		return err
	}

	for _, requiredProperty := range requiredProperties {
		if _, exists := allProperties[requiredProperty]; !exists {
			return fmt.Errorf("no value given for required property %v", requiredProperty)
		}
	}

	varSensorGroupAssignmentsGetItem := _SensorGroupAssignmentsGetItem{}

	decoder := json.NewDecoder(bytes.NewReader(data))
	decoder.DisallowUnknownFields()
	err = decoder.Decode(&varSensorGroupAssignmentsGetItem)

	if err != nil {
		return err
	}

	*o = SensorGroupAssignmentsGetItem(varSensorGroupAssignmentsGetItem)

	return err
}

type NullableSensorGroupAssignmentsGetItem struct {
	value *SensorGroupAssignmentsGetItem
	isSet bool
}

func (v NullableSensorGroupAssignmentsGetItem) Get() *SensorGroupAssignmentsGetItem {
	return v.value
}

func (v *NullableSensorGroupAssignmentsGetItem) Set(val *SensorGroupAssignmentsGetItem) {
	v.value = val
	v.isSet = true
}

func (v NullableSensorGroupAssignmentsGetItem) IsSet() bool {
	return v.isSet
}

func (v *NullableSensorGroupAssignmentsGetItem) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableSensorGroupAssignmentsGetItem(
	val *SensorGroupAssignmentsGetItem,
) *NullableSensorGroupAssignmentsGetItem {
	return &NullableSensorGroupAssignmentsGetItem{value: val, isSet: true}
}

func (v NullableSensorGroupAssignmentsGetItem) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableSensorGroupAssignmentsGetItem) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}
