/*
Configuration Api

Nice description goes here

API version: 1.9.0
Contact: support@capenetworks.com
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package config_api_client

import (
	"bytes"
	"encoding/json"
	"fmt"
	"time"
)

// checks if the WiredNetwork type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &WiredNetwork{}

// WiredNetwork struct for WiredNetwork
type WiredNetwork struct {
	Uid                  string         `json:"uid"`
	Alias                string         `json:"alias"`
	IpVersion            string         `json:"ip_version"`
	SensorCount          int32          `json:"sensor_count"`
	UpdatedAt            time.Time      `json:"updated_at"`
	CreatedAt            time.Time      `json:"created_at"`
	Disabled             bool           `json:"disabled"`
	Security             NullableString `json:"security"`
	DnsLookupDomain      NullableString `json:"dns_lookup_domain"`
	DisableEdns          bool           `json:"disable_edns"`
	UseDns64             bool           `json:"use_dns64"`
	ExternalConnectivity bool           `json:"external_connectivity"`
	VlanId               NullableInt32  `json:"vlan_id"`
}

type _WiredNetwork WiredNetwork

// NewWiredNetwork instantiates a new WiredNetwork object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewWiredNetwork(uid string, alias string, ipVersion string, sensorCount int32, updatedAt time.Time, createdAt time.Time, disabled bool, security NullableString, dnsLookupDomain NullableString, disableEdns bool, useDns64 bool, externalConnectivity bool, vlanId NullableInt32) *WiredNetwork {
	this := WiredNetwork{}
	this.Uid = uid
	this.Alias = alias
	this.IpVersion = ipVersion
	this.SensorCount = sensorCount
	this.UpdatedAt = updatedAt
	this.CreatedAt = createdAt
	this.Disabled = disabled
	this.Security = security
	this.DnsLookupDomain = dnsLookupDomain
	this.DisableEdns = disableEdns
	this.UseDns64 = useDns64
	this.ExternalConnectivity = externalConnectivity
	this.VlanId = vlanId
	return &this
}

// NewWiredNetworkWithDefaults instantiates a new WiredNetwork object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewWiredNetworkWithDefaults() *WiredNetwork {
	this := WiredNetwork{}
	return &this
}

// GetUid returns the Uid field value
func (o *WiredNetwork) GetUid() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.Uid
}

// GetUidOk returns a tuple with the Uid field value
// and a boolean to check if the value has been set.
func (o *WiredNetwork) GetUidOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.Uid, true
}

// SetUid sets field value
func (o *WiredNetwork) SetUid(v string) {
	o.Uid = v
}

// GetAlias returns the Alias field value
func (o *WiredNetwork) GetAlias() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.Alias
}

// GetAliasOk returns a tuple with the Alias field value
// and a boolean to check if the value has been set.
func (o *WiredNetwork) GetAliasOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.Alias, true
}

// SetAlias sets field value
func (o *WiredNetwork) SetAlias(v string) {
	o.Alias = v
}

// GetIpVersion returns the IpVersion field value
func (o *WiredNetwork) GetIpVersion() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.IpVersion
}

// GetIpVersionOk returns a tuple with the IpVersion field value
// and a boolean to check if the value has been set.
func (o *WiredNetwork) GetIpVersionOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.IpVersion, true
}

// SetIpVersion sets field value
func (o *WiredNetwork) SetIpVersion(v string) {
	o.IpVersion = v
}

// GetSensorCount returns the SensorCount field value
func (o *WiredNetwork) GetSensorCount() int32 {
	if o == nil {
		var ret int32
		return ret
	}

	return o.SensorCount
}

// GetSensorCountOk returns a tuple with the SensorCount field value
// and a boolean to check if the value has been set.
func (o *WiredNetwork) GetSensorCountOk() (*int32, bool) {
	if o == nil {
		return nil, false
	}
	return &o.SensorCount, true
}

// SetSensorCount sets field value
func (o *WiredNetwork) SetSensorCount(v int32) {
	o.SensorCount = v
}

// GetUpdatedAt returns the UpdatedAt field value
func (o *WiredNetwork) GetUpdatedAt() time.Time {
	if o == nil {
		var ret time.Time
		return ret
	}

	return o.UpdatedAt
}

// GetUpdatedAtOk returns a tuple with the UpdatedAt field value
// and a boolean to check if the value has been set.
func (o *WiredNetwork) GetUpdatedAtOk() (*time.Time, bool) {
	if o == nil {
		return nil, false
	}
	return &o.UpdatedAt, true
}

// SetUpdatedAt sets field value
func (o *WiredNetwork) SetUpdatedAt(v time.Time) {
	o.UpdatedAt = v
}

// GetCreatedAt returns the CreatedAt field value
func (o *WiredNetwork) GetCreatedAt() time.Time {
	if o == nil {
		var ret time.Time
		return ret
	}

	return o.CreatedAt
}

// GetCreatedAtOk returns a tuple with the CreatedAt field value
// and a boolean to check if the value has been set.
func (o *WiredNetwork) GetCreatedAtOk() (*time.Time, bool) {
	if o == nil {
		return nil, false
	}
	return &o.CreatedAt, true
}

// SetCreatedAt sets field value
func (o *WiredNetwork) SetCreatedAt(v time.Time) {
	o.CreatedAt = v
}

// GetDisabled returns the Disabled field value
func (o *WiredNetwork) GetDisabled() bool {
	if o == nil {
		var ret bool
		return ret
	}

	return o.Disabled
}

// GetDisabledOk returns a tuple with the Disabled field value
// and a boolean to check if the value has been set.
func (o *WiredNetwork) GetDisabledOk() (*bool, bool) {
	if o == nil {
		return nil, false
	}
	return &o.Disabled, true
}

// SetDisabled sets field value
func (o *WiredNetwork) SetDisabled(v bool) {
	o.Disabled = v
}

// GetSecurity returns the Security field value
// If the value is explicit nil, the zero value for string will be returned
func (o *WiredNetwork) GetSecurity() string {
	if o == nil || o.Security.Get() == nil {
		var ret string
		return ret
	}

	return *o.Security.Get()
}

// GetSecurityOk returns a tuple with the Security field value
// and a boolean to check if the value has been set.
// NOTE: If the value is an explicit nil, `nil, true` will be returned
func (o *WiredNetwork) GetSecurityOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return o.Security.Get(), o.Security.IsSet()
}

// SetSecurity sets field value
func (o *WiredNetwork) SetSecurity(v string) {
	o.Security.Set(&v)
}

// GetDnsLookupDomain returns the DnsLookupDomain field value
// If the value is explicit nil, the zero value for string will be returned
func (o *WiredNetwork) GetDnsLookupDomain() string {
	if o == nil || o.DnsLookupDomain.Get() == nil {
		var ret string
		return ret
	}

	return *o.DnsLookupDomain.Get()
}

// GetDnsLookupDomainOk returns a tuple with the DnsLookupDomain field value
// and a boolean to check if the value has been set.
// NOTE: If the value is an explicit nil, `nil, true` will be returned
func (o *WiredNetwork) GetDnsLookupDomainOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return o.DnsLookupDomain.Get(), o.DnsLookupDomain.IsSet()
}

// SetDnsLookupDomain sets field value
func (o *WiredNetwork) SetDnsLookupDomain(v string) {
	o.DnsLookupDomain.Set(&v)
}

// GetDisableEdns returns the DisableEdns field value
func (o *WiredNetwork) GetDisableEdns() bool {
	if o == nil {
		var ret bool
		return ret
	}

	return o.DisableEdns
}

// GetDisableEdnsOk returns a tuple with the DisableEdns field value
// and a boolean to check if the value has been set.
func (o *WiredNetwork) GetDisableEdnsOk() (*bool, bool) {
	if o == nil {
		return nil, false
	}
	return &o.DisableEdns, true
}

// SetDisableEdns sets field value
func (o *WiredNetwork) SetDisableEdns(v bool) {
	o.DisableEdns = v
}

// GetUseDns64 returns the UseDns64 field value
func (o *WiredNetwork) GetUseDns64() bool {
	if o == nil {
		var ret bool
		return ret
	}

	return o.UseDns64
}

// GetUseDns64Ok returns a tuple with the UseDns64 field value
// and a boolean to check if the value has been set.
func (o *WiredNetwork) GetUseDns64Ok() (*bool, bool) {
	if o == nil {
		return nil, false
	}
	return &o.UseDns64, true
}

// SetUseDns64 sets field value
func (o *WiredNetwork) SetUseDns64(v bool) {
	o.UseDns64 = v
}

// GetExternalConnectivity returns the ExternalConnectivity field value
func (o *WiredNetwork) GetExternalConnectivity() bool {
	if o == nil {
		var ret bool
		return ret
	}

	return o.ExternalConnectivity
}

// GetExternalConnectivityOk returns a tuple with the ExternalConnectivity field value
// and a boolean to check if the value has been set.
func (o *WiredNetwork) GetExternalConnectivityOk() (*bool, bool) {
	if o == nil {
		return nil, false
	}
	return &o.ExternalConnectivity, true
}

// SetExternalConnectivity sets field value
func (o *WiredNetwork) SetExternalConnectivity(v bool) {
	o.ExternalConnectivity = v
}

// GetVlanId returns the VlanId field value
// If the value is explicit nil, the zero value for int32 will be returned
func (o *WiredNetwork) GetVlanId() int32 {
	if o == nil || o.VlanId.Get() == nil {
		var ret int32
		return ret
	}

	return *o.VlanId.Get()
}

// GetVlanIdOk returns a tuple with the VlanId field value
// and a boolean to check if the value has been set.
// NOTE: If the value is an explicit nil, `nil, true` will be returned
func (o *WiredNetwork) GetVlanIdOk() (*int32, bool) {
	if o == nil {
		return nil, false
	}
	return o.VlanId.Get(), o.VlanId.IsSet()
}

// SetVlanId sets field value
func (o *WiredNetwork) SetVlanId(v int32) {
	o.VlanId.Set(&v)
}

func (o WiredNetwork) MarshalJSON() ([]byte, error) {
	toSerialize, err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o WiredNetwork) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	toSerialize["uid"] = o.Uid
	toSerialize["alias"] = o.Alias
	toSerialize["ip_version"] = o.IpVersion
	toSerialize["sensor_count"] = o.SensorCount
	toSerialize["updated_at"] = o.UpdatedAt
	toSerialize["created_at"] = o.CreatedAt
	toSerialize["disabled"] = o.Disabled
	toSerialize["security"] = o.Security.Get()
	toSerialize["dns_lookup_domain"] = o.DnsLookupDomain.Get()
	toSerialize["disable_edns"] = o.DisableEdns
	toSerialize["use_dns64"] = o.UseDns64
	toSerialize["external_connectivity"] = o.ExternalConnectivity
	toSerialize["vlan_id"] = o.VlanId.Get()
	return toSerialize, nil
}

func (o *WiredNetwork) UnmarshalJSON(data []byte) (err error) {
	// This validates that all required properties are included in the JSON object
	// by unmarshalling the object into a generic map with string keys and checking
	// that every required field exists as a key in the generic map.
	requiredProperties := []string{
		"uid",
		"alias",
		"ip_version",
		"sensor_count",
		"updated_at",
		"created_at",
		"disabled",
		"security",
		"dns_lookup_domain",
		"disable_edns",
		"use_dns64",
		"external_connectivity",
		"vlan_id",
	}

	allProperties := make(map[string]interface{})

	err = json.Unmarshal(data, &allProperties)

	if err != nil {
		return err
	}

	for _, requiredProperty := range requiredProperties {
		if _, exists := allProperties[requiredProperty]; !exists {
			return fmt.Errorf("no value given for required property %v", requiredProperty)
		}
	}

	varWiredNetwork := _WiredNetwork{}

	decoder := json.NewDecoder(bytes.NewReader(data))
	decoder.DisallowUnknownFields()
	err = decoder.Decode(&varWiredNetwork)

	if err != nil {
		return err
	}

	*o = WiredNetwork(varWiredNetwork)

	return err
}

type NullableWiredNetwork struct {
	value *WiredNetwork
	isSet bool
}

func (v NullableWiredNetwork) Get() *WiredNetwork {
	return v.value
}

func (v *NullableWiredNetwork) Set(val *WiredNetwork) {
	v.value = val
	v.isSet = true
}

func (v NullableWiredNetwork) IsSet() bool {
	return v.isSet
}

func (v *NullableWiredNetwork) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableWiredNetwork(val *WiredNetwork) *NullableWiredNetwork {
	return &NullableWiredNetwork{value: val, isSet: true}
}

func (v NullableWiredNetwork) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableWiredNetwork) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}
