/*
Configuration Api

Nice description goes here

API version: 1.11.0
Contact: support@capenetworks.com
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package config_api_client

import (
	"bytes"
	"encoding/json"
	"fmt"
)

// checks if the NetworkGroupAssignmentsResponse type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &NetworkGroupAssignmentsResponse{}

// NetworkGroupAssignmentsResponse struct for NetworkGroupAssignmentsResponse
type NetworkGroupAssignmentsResponse struct {
	NetworkGroupAssignments []NetworkGroupAssignmentsItem `json:"network_group_assignments"`
	Pagination              PaginationDetails             `json:"pagination"`
}

type _NetworkGroupAssignmentsResponse NetworkGroupAssignmentsResponse

// NewNetworkGroupAssignmentsResponse instantiates a new NetworkGroupAssignmentsResponse object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewNetworkGroupAssignmentsResponse(networkGroupAssignments []NetworkGroupAssignmentsItem, pagination PaginationDetails) *NetworkGroupAssignmentsResponse {
	this := NetworkGroupAssignmentsResponse{}
	this.NetworkGroupAssignments = networkGroupAssignments
	this.Pagination = pagination
	return &this
}

// NewNetworkGroupAssignmentsResponseWithDefaults instantiates a new NetworkGroupAssignmentsResponse object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewNetworkGroupAssignmentsResponseWithDefaults() *NetworkGroupAssignmentsResponse {
	this := NetworkGroupAssignmentsResponse{}
	return &this
}

// GetNetworkGroupAssignments returns the NetworkGroupAssignments field value
func (o *NetworkGroupAssignmentsResponse) GetNetworkGroupAssignments() []NetworkGroupAssignmentsItem {
	if o == nil {
		var ret []NetworkGroupAssignmentsItem
		return ret
	}

	return o.NetworkGroupAssignments
}

// GetNetworkGroupAssignmentsOk returns a tuple with the NetworkGroupAssignments field value
// and a boolean to check if the value has been set.
func (o *NetworkGroupAssignmentsResponse) GetNetworkGroupAssignmentsOk() ([]NetworkGroupAssignmentsItem, bool) {
	if o == nil {
		return nil, false
	}
	return o.NetworkGroupAssignments, true
}

// SetNetworkGroupAssignments sets field value
func (o *NetworkGroupAssignmentsResponse) SetNetworkGroupAssignments(v []NetworkGroupAssignmentsItem) {
	o.NetworkGroupAssignments = v
}

// GetPagination returns the Pagination field value
func (o *NetworkGroupAssignmentsResponse) GetPagination() PaginationDetails {
	if o == nil {
		var ret PaginationDetails
		return ret
	}

	return o.Pagination
}

// GetPaginationOk returns a tuple with the Pagination field value
// and a boolean to check if the value has been set.
func (o *NetworkGroupAssignmentsResponse) GetPaginationOk() (*PaginationDetails, bool) {
	if o == nil {
		return nil, false
	}
	return &o.Pagination, true
}

// SetPagination sets field value
func (o *NetworkGroupAssignmentsResponse) SetPagination(v PaginationDetails) {
	o.Pagination = v
}

func (o NetworkGroupAssignmentsResponse) MarshalJSON() ([]byte, error) {
	toSerialize, err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o NetworkGroupAssignmentsResponse) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	toSerialize["network_group_assignments"] = o.NetworkGroupAssignments
	toSerialize["pagination"] = o.Pagination
	return toSerialize, nil
}

func (o *NetworkGroupAssignmentsResponse) UnmarshalJSON(data []byte) (err error) {
	// This validates that all required properties are included in the JSON object
	// by unmarshalling the object into a generic map with string keys and checking
	// that every required field exists as a key in the generic map.
	requiredProperties := []string{
		"network_group_assignments",
		"pagination",
	}

	allProperties := make(map[string]interface{})

	err = json.Unmarshal(data, &allProperties)

	if err != nil {
		return err
	}

	for _, requiredProperty := range requiredProperties {
		if _, exists := allProperties[requiredProperty]; !exists {
			return fmt.Errorf("no value given for required property %v", requiredProperty)
		}
	}

	varNetworkGroupAssignmentsResponse := _NetworkGroupAssignmentsResponse{}

	decoder := json.NewDecoder(bytes.NewReader(data))
	decoder.DisallowUnknownFields()
	err = decoder.Decode(&varNetworkGroupAssignmentsResponse)

	if err != nil {
		return err
	}

	*o = NetworkGroupAssignmentsResponse(varNetworkGroupAssignmentsResponse)

	return err
}

type NullableNetworkGroupAssignmentsResponse struct {
	value *NetworkGroupAssignmentsResponse
	isSet bool
}

func (v NullableNetworkGroupAssignmentsResponse) Get() *NetworkGroupAssignmentsResponse {
	return v.value
}

func (v *NullableNetworkGroupAssignmentsResponse) Set(val *NetworkGroupAssignmentsResponse) {
	v.value = val
	v.isSet = true
}

func (v NullableNetworkGroupAssignmentsResponse) IsSet() bool {
	return v.isSet
}

func (v *NullableNetworkGroupAssignmentsResponse) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableNetworkGroupAssignmentsResponse(val *NetworkGroupAssignmentsResponse) *NullableNetworkGroupAssignmentsResponse {
	return &NullableNetworkGroupAssignmentsResponse{value: val, isSet: true}
}

func (v NullableNetworkGroupAssignmentsResponse) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableNetworkGroupAssignmentsResponse) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}
