/*
FastAPI

No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)

API version: 1.0.0
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package config_api_client

import (
	"bytes"
	"encoding/json"
	"fmt"
)

// checks if the LivenessResponse type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &LivenessResponse{}

// LivenessResponse struct for LivenessResponse
type LivenessResponse struct {
	status string `json:"status"`
}

type _LivenessResponse LivenessResponse

// NewLivenessResponse instantiates a new LivenessResponse object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewLivenessResponse(status string) *LivenessResponse {
	this := LivenessResponse{}
	this.Status = status
	return &this
}

// NewLivenessResponseWithDefaults instantiates a new LivenessResponse object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewLivenessResponseWithDefaults() *LivenessResponse {
	this := LivenessResponse{}
	return &this
}

// GetStatus returns the Status field value
func (o *LivenessResponse) GetStatus() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.Status
}

// GetStatusOk returns a tuple with the Status field value
// and a boolean to check if the value has been set.
func (o *LivenessResponse) GetStatusOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.Status, true
}

// SetStatus sets field value
func (o *LivenessResponse) SetStatus(v string) {
	o.Status = v
}

func (o LivenessResponse) MarshalJSON() ([]byte, error) {
	toSerialize, err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o LivenessResponse) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	toSerialize["status"] = o.Status
	return toSerialize, nil
}

func (o *LivenessResponse) UnmarshalJSON(data []byte) (err error) {
	// This validates that all required properties are included in the JSON object
	// by unmarshalling the object into a generic map with string keys and checking
	// that every required field exists as a key in the generic map.
	requiredProperties := []string{
		"status",
	}

	allProperties := make(map[string]interface{})

	err = json.Unmarshal(data, &allProperties)

	if err != nil {
		return err
	}

	for _, requiredProperty := range requiredProperties {
		if _, exists := allProperties[requiredProperty]; !exists {
			return fmt.Errorf("no value given for required property %v", requiredProperty)
		}
	}

	varLivenessResponse := _LivenessResponse{}

	decoder := json.NewDecoder(bytes.NewReader(data))
	decoder.DisallowUnknownFields()
	err = decoder.Decode(&varLivenessResponse)

	if err != nil {
		return err
	}

	*o = LivenessResponse(varLivenessResponse)

	return err
}

type NullableLivenessResponse struct {
	value *LivenessResponse
	isSet bool
}

func (v NullableLivenessResponse) Get() *LivenessResponse {
	return v.value
}

func (v *NullableLivenessResponse) Set(val *LivenessResponse) {
	v.value = val
	v.isSet = true
}

func (v NullableLivenessResponse) IsSet() bool {
	return v.isSet
}

func (v *NullableLivenessResponse) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableLivenessResponse(val *LivenessResponse) *NullableLivenessResponse {
	return &NullableLivenessResponse{value: val, isSet: true}
}

func (v NullableLivenessResponse) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableLivenessResponse) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}
